apiVersion: 1

datasources:
  - name: BB Gold PostgreSQL
    type: postgres
    uid: bb-gold-postgres
    access: proxy
    url: postgres:5432
    database: bb_gold
    user: bb_user
    secureJsonData:
      password: bb_secure_password_2024
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true